tarte_au_citron.settings:
  type: config_entity
  label: 'Tarte au citron settings'
  mapping:
    privacyUrl:
      type: string
      label: 'Privacy policy url'
    hashtag:
      type: string
      label: 'Open the panel with this hashtag'
    cookieName:
      type: string
      label: 'Cookie name'
    orientation:
      type: string
      label: 'Banner position (top - middle - bottom)'
    mandatory:
      type: boolean
      label: 'Show a message about mandatory cookies'
    showAlertSmall:
      type: boolean
      label: 'Show the small banner on bottom right'
    cookieslist:
      type: boolean
      label: 'Show the cookie list'
    showIcon:
      type: boolean
      label: 'Show cookie icon to manage cookies'
    iconPosition:
      type: string
      label: 'Position of the icon (bottom right - bottom left - top right - top left)'
    adblocker:
      type: boolean
      label: 'Show a Warning if an adblocker is detected'
    DenyAllCta:
      type: boolean
      label: 'Show the deny all button'
    AcceptAllCta:
      type: boolean
      label: 'Show the accept all button when highPrivacy on'
    highPrivacy:
      type: boolean
      label: 'HIGHLY RECOMMANDED Disable auto consent'
    handleBrowserDNTRequest:
      type: boolean
      label: 'If Do Not Track == 1, disallow all'
    removeCredit:
      type: boolean
      label: 'Remove credit link'
    moreInfoLink:
      type: boolean
      label: 'Show more info link'
    useExternalCss:
      type: boolean
      label: 'If false, the tarteaucitron.css file will be loaded'
    readmoreLink:
      type: string
      label: 'Change the default readmore link pointing to tarteaucitron.io'
    services:
      type: sequence
      label: 'Services'
      sequence:
        type: string
        label: 'Service'

tarte_au_citron.texts.settings:
  type: config_entity
  label: 'Tarte au citron texts settings'
  mapping:
    middleBarHead:
      type: string
      translatable: false
      label: '☝ 🍪'
    adblock:
      type: string
      translatable: false
      label: 'Hello! This site is transparent and lets you chose the 3rd party services you want to allow.'
    adblock_call:
      type: string
      translatable: false
      label: 'Please disable your adblocker to start customizing.'
    reload:
      type: string
      translatable: false
      label: 'Refresh the page'
    alertBigScroll:
      type: string
      translatable: false
      label: 'By continuing to scroll,'
    alertBigClick:
      type: string
      translatable: false
      label: 'If you continue to browse this website,'
    alertBig:
      type: string
      translatable: false
      label: 'you are allowing all third-party services'
    alertBigPrivacy:
      type: string
      translatable: false
      label: 'This site uses cookies and gives you control over what you want to activate'
    alertSmall:
      type: string
      translatable: false
      label: 'Manage services'
    personalize:
      type: string
      translatable: false
      label: 'Personalize'
    acceptAll:
      type: string
      translatable: false
      label: 'OK, accept all'
    close:
      type: string
      translatable: false
      label: 'Close'
    privacyUrl:
      type: string
      translatable: false
      label: 'Privacy policy'
    all:
      type: string
      translatable: false
      label: 'Preference for all services'
    info:
      type: string
      translatable: false
      label: 'Protecting your privacy'
    disclaimer:
      type: string
      translatable: false
      label: 'By allowing these third party services, you accept their cookies and the use of tracking technologies necessary for their proper functioning.'
    allow:
      type: string
      translatable: false
      label: 'Allow'
    deny:
      type: string
      translatable: false
      label: 'Deny'
    noCookie:
      type: string
      translatable: false
      label: 'This service does not use cookie.'
    useCookie:
      type: string
      translatable: false
      label: 'This service can install'
    useCookieCurrent:
      type: string
      translatable: false
      label: 'This service has installed'
    useNoCookie:
      type: string
      translatable: false
      label: 'This service has not installed any cookie.'
    more:
      type: string
      translatable: false
      label: 'Read more'
    source:
      type: string
      translatable: false
      label: 'View the official website'
    credit:
      type: string
      translatable: false
      label: 'Cookies manager by tarteaucitron.js'
    noServices:
      type: string
      translatable: false
      label: 'This website does not use any cookie requiring your consent.'
    toggleInfoBox:
      type: string
      translatable: false
      label: 'Show/hide informations about cookie storage'
    title:
      type: string
      translatable: false
      label: 'Cookies management panel'
    cookieDetail:
      type: string
      translatable: false
      label: 'Cookie detail for'
    ourSite:
      type: string
      translatable: false
      label: 'on our site'
    newWindow:
      type: string
      translatable: false
      label: '(new window)'
    allowAll:
      type: string
      translatable: false
      label: 'Allow all cookies'
    denyAll:
      type: string
      translatable: false
      label: 'Deny all cookies'
    fallback:
      type: string
      translatable: false
      label: 'is disabled.'
    ads_title:
      type: string
      translatable: false
      label: 'Advertising network'
    ads_details:
      type: string
      translatable: false
      label: 'Ad networks can generate revenue by selling advertising space on the site.'
    analytic_title:
      type: string
      translatable: false
      label: 'Audience measurement'
    analytic_details:
      type: string
      translatable: false
      label: 'The audience measurement services used to generate useful statistics attendance to improve the site.'
    social_title:
      type: string
      translatable: false
      label: 'Social networks'
    social_details:
      type: string
      translatable: false
      label: 'Social networks can improve the usability of the site and help to promote it via the shares.'
    video_title:
      type: string
      translatable: false
      label: 'Videos'
    video_details:
      type: string
      translatable: false
      label: 'Video sharing services help to add rich media on the site and increase its visibility.'
    comment_title:
      type: string
      translatable: false
      label: 'Comments'
    comment_details:
      type: string
      translatable: false
      label: 'Comments managers facilitate the filing of comments and fight against spam.'
    support_title:
      type: string
      translatable: false
      label: 'Support'
    support_details:
      type: string
      translatable: false
      label: 'Support services allow you to get in touch with the site team and help to improve it.'
    api_title:
      type: string
      translatable: false
      label: 'APIs'
    api_details:
      type: string
      translatable: false
      label: 'APIs are used to load scripts: geolocation, search engines, translations, ...'
    other_title:
      type: string
      translatable: false
      label: 'Other'
    other_details:
      type: string
      translatable: false
      label: 'Services to display web content.'
    mandatoryTitle:
      type: string
      translatable: false
      label: 'Mandatory cookies'
    mandatoryText:
      type: string
      translatable: false
      label: 'This site uses cookies necessary for its proper functioning which cannot be deactivated.'
