<?php

/**
 * @file
 * Provides primary Drupal hook implementations.
 */

/**
 * Implements hook_library_info_alter().
 */
function tarte_au_citron_addtoany_library_info_alter(&$libraries, $extension) {
  if ($extension === 'addtoany') {
    unset($libraries['addtoany']['js']['https://static.addtoany.com/menu/page.js']);
  }
}

/**
 * Implements hook_page_attachments().
 */
function tarte_au_citron_addtoany_page_attachments(&$page) {
  /**
   * @var $serviceManager \Drupal\tarte_au_citron\ServicesManagerInterface
   */
  $serviceManager = \Drupal::getContainer()
    ->get('tarte_au_citron.services_manager');
  if ($serviceManager->isNeeded() && $serviceManager->isServiceEnabled('drupal_addtoany')) {
    return;
  }

  //If tarte au citron is bypassed, add addtoany js
  $route = \Drupal::routeMatch()->getRouteObject();
  if (!\Drupal::service('router.admin_context')->isAdminRoute($route)) {
    $page['#attached']['library'][] = 'tarte_au_citron_addtoany/addtoany_lib';
  }
}
